# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_storage_dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_CreateStorageDialog(object):
    def setupUi(self, CreateStorageDialog):
        CreateStorageDialog.setObjectName("CreateStorageDialog")
        CreateStorageDialog.resize(405, 330)
        self.verticalLayout_2 = QtGui.QVBoxLayout(CreateStorageDialog)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_widget = QtGui.QWidget(CreateStorageDialog)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.main_widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_storage_title_lbl = QtGui.QLabel(self.main_widget)
        self.create_storage_title_lbl.setObjectName("create_storage_title_lbl")
        self.verticalLayout.addWidget(self.create_storage_title_lbl)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.create_storage_header_lbl = QtGui.QLabel(self.main_widget)
        self.create_storage_header_lbl.setWordWrap(True)
        self.create_storage_header_lbl.setObjectName("create_storage_header_lbl")
        self.verticalLayout.addWidget(self.create_storage_header_lbl)
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.storage_name_layout = QtGui.QHBoxLayout()
        self.storage_name_layout.setSpacing(4)
        self.storage_name_layout.setObjectName("storage_name_layout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.storage_name_layout.addItem(spacerItem2)
        self.storage_name_lbl = QtGui.QLabel(self.main_widget)
        self.storage_name_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.storage_name_lbl.setObjectName("storage_name_lbl")
        self.storage_name_layout.addWidget(self.storage_name_lbl)
        self.storage_name = QtGui.QLineEdit(self.main_widget)
        self.storage_name.setObjectName("storage_name")
        self.storage_name_layout.addWidget(self.storage_name)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.storage_name_layout.addItem(spacerItem3)
        self.storage_name_layout.setStretch(0, 5)
        self.storage_name_layout.setStretch(2, 15)
        self.verticalLayout.addLayout(self.storage_name_layout)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.paths_group_box = QtGui.QGroupBox(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paths_group_box.sizePolicy().hasHeightForWidth())
        self.paths_group_box.setSizePolicy(sizePolicy)
        self.paths_group_box.setMinimumSize(QtCore.QSize(0, 0))
        self.paths_group_box.setObjectName("paths_group_box")
        self.gridLayout = QtGui.QGridLayout(self.paths_group_box)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.windows_path = QtGui.QLineEdit(self.paths_group_box)
        self.windows_path.setObjectName("windows_path")
        self.gridLayout.addWidget(self.windows_path, 2, 1, 1, 1)
        self.mac_path_lbl = QtGui.QLabel(self.paths_group_box)
        self.mac_path_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mac_path_lbl.setObjectName("mac_path_lbl")
        self.gridLayout.addWidget(self.mac_path_lbl, 1, 0, 1, 1)
        self.linux_path = QtGui.QLineEdit(self.paths_group_box)
        self.linux_path.setObjectName("linux_path")
        self.gridLayout.addWidget(self.linux_path, 0, 1, 1, 1)
        self.mac_path = QtGui.QLineEdit(self.paths_group_box)
        self.mac_path.setObjectName("mac_path")
        self.gridLayout.addWidget(self.mac_path, 1, 1, 1, 1)
        self.windows_path_lbl = QtGui.QLabel(self.paths_group_box)
        self.windows_path_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windows_path_lbl.setObjectName("windows_path_lbl")
        self.gridLayout.addWidget(self.windows_path_lbl, 2, 0, 1, 1)
        self.linux_browse = QtGui.QToolButton(self.paths_group_box)
        self.linux_browse.setObjectName("linux_browse")
        self.gridLayout.addWidget(self.linux_browse, 0, 2, 1, 1)
        self.linux_path_lbl = QtGui.QLabel(self.paths_group_box)
        self.linux_path_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linux_path_lbl.setObjectName("linux_path_lbl")
        self.gridLayout.addWidget(self.linux_path_lbl, 0, 0, 1, 1)
        self.windows_browse = QtGui.QToolButton(self.paths_group_box)
        self.windows_browse.setObjectName("windows_browse")
        self.gridLayout.addWidget(self.windows_browse, 2, 2, 1, 1)
        self.mac_browse = QtGui.QToolButton(self.paths_group_box)
        self.mac_browse.setObjectName("mac_browse")
        self.gridLayout.addWidget(self.mac_browse, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.paths_group_box)
        spacerItem5 = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.info = QtGui.QLabel(self.main_widget)
        self.info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.verticalLayout_2.addWidget(self.main_widget)
        self.button_box = QtGui.QDialogButtonBox(CreateStorageDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.button_box.setCenterButtons(False)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box)

        self.retranslateUi(CreateStorageDialog)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL("accepted()"), CreateStorageDialog.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL("rejected()"), CreateStorageDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateStorageDialog)

    def retranslateUi(self, CreateStorageDialog):
        CreateStorageDialog.setWindowTitle(QtGui.QApplication.translate("CreateStorageDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.create_storage_title_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Create New Local Storage</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.create_storage_header_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "<html><head/><body><p>Create a new Local Storage that defines where files on disk will live. This storage can be associated with one or more project data roots and defines paths for each operating system used by your studio. <a href=\"https://support.shotgunsoftware.com/hc/en-us/articles/219030938-Linking-to-local-files#how_to_set_up\"><span style=\" text-decoration: underline; color:#0000ff;\">More info…</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.storage_name_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "Storage Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.paths_group_box.setTitle(QtGui.QApplication.translate("CreateStorageDialog", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_path_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "Mac:", None, QtGui.QApplication.UnicodeUTF8))
        self.windows_path_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "Windows:", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_browse.setText(QtGui.QApplication.translate("CreateStorageDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_path_lbl.setText(QtGui.QApplication.translate("CreateStorageDialog", "Linux:", None, QtGui.QApplication.UnicodeUTF8))
        self.windows_browse.setText(QtGui.QApplication.translate("CreateStorageDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_browse.setText(QtGui.QApplication.translate("CreateStorageDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setText(QtGui.QApplication.translate("CreateStorageDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))

