# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_project.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(453, 467)
        Wizard.setModal(True)
        Wizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        Wizard.setOptions(QtGui.QWizard.CancelButtonOnLeft|QtGui.QWizard.DisabledBackButtonOnLastPage|QtGui.QWizard.IndependentPages)
        Wizard.setTitleFormat(QtCore.Qt.RichText)
        self.setup_type_page = QtGui.QWizardPage()
        self.setup_type_page.setStyleSheet("QRadioButton {\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 12px;\n"
"    color: rgb(120, 120,120);\n"
"}")
        self.setup_type_page.setObjectName("setup_type_page")
        self.verticalLayout = QtGui.QVBoxLayout(self.setup_type_page)
        self.verticalLayout.setContentsMargins(25, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.select_standard = QtGui.QRadioButton(self.setup_type_page)
        self.select_standard.setChecked(True)
        self.select_standard.setObjectName("select_standard")
        self.verticalLayout.addWidget(self.select_standard)
        self.label_standard = QtGui.QLabel(self.setup_type_page)
        self.label_standard.setIndent(20)
        self.label_standard.setObjectName("label_standard")
        self.verticalLayout.addWidget(self.label_standard)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.select_project = QtGui.QRadioButton(self.setup_type_page)
        self.select_project.setObjectName("select_project")
        self.verticalLayout.addWidget(self.select_project)
        self.label_project = QtGui.QLabel(self.setup_type_page)
        self.label_project.setIndent(20)
        self.label_project.setObjectName("label_project")
        self.verticalLayout.addWidget(self.label_project)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.select_github = QtGui.QRadioButton(self.setup_type_page)
        self.select_github.setObjectName("select_github")
        self.verticalLayout.addWidget(self.select_github)
        self.label_github = QtGui.QLabel(self.setup_type_page)
        self.label_github.setIndent(20)
        self.label_github.setObjectName("label_github")
        self.verticalLayout.addWidget(self.label_github)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.select_disk = QtGui.QRadioButton(self.setup_type_page)
        self.select_disk.setObjectName("select_disk")
        self.verticalLayout.addWidget(self.select_disk)
        self.label_disk = QtGui.QLabel(self.setup_type_page)
        self.label_disk.setIndent(20)
        self.label_disk.setObjectName("label_disk")
        self.verticalLayout.addWidget(self.label_disk)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        Wizard.addPage(self.setup_type_page)
        self.project_config_page = QtGui.QWizardPage()
        self.project_config_page.setObjectName("project_config_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.project_config_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_list = QtGui.QListWidget(self.project_config_page)
        self.project_list.setFrameShape(QtGui.QFrame.NoFrame)
        self.project_list.setObjectName("project_list")
        self.verticalLayout_2.addWidget(self.project_list)
        Wizard.addPage(self.project_config_page)
        self.github_config_page = QtGui.QWizardPage()
        self.github_config_page.setObjectName("github_config_page")
        self.gridLayout = QtGui.QGridLayout(self.github_config_page)
        self.gridLayout.setContentsMargins(30, 30, 60, 30)
        self.gridLayout.setObjectName("gridLayout")
        self.github_url = QtGui.QLineEdit(self.github_config_page)
        self.github_url.setObjectName("github_url")
        self.gridLayout.addWidget(self.github_url, 0, 1, 1, 1)
        self.octocat = QtGui.QLabel(self.github_config_page)
        self.octocat.setMaximumSize(QtCore.QSize(30, 30))
        self.octocat.setText("")
        self.octocat.setPixmap(QtGui.QPixmap(":/res/octocats/original.png"))
        self.octocat.setScaledContents(True)
        self.octocat.setObjectName("octocat")
        self.gridLayout.addWidget(self.octocat, 0, 0, 1, 1)
        Wizard.addPage(self.github_config_page)
        self.disk_config_page = QtGui.QWizardPage()
        self.disk_config_page.setObjectName("disk_config_page")
        self.gridLayout_2 = QtGui.QGridLayout(self.disk_config_page)
        self.gridLayout_2.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path = QtGui.QLineEdit(self.disk_config_page)
        self.path.setObjectName("path")
        self.gridLayout_2.addWidget(self.path, 0, 0, 1, 1)
        self.browse_button = QtGui.QPushButton(self.disk_config_page)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_2.addWidget(self.browse_button, 0, 1, 1, 1)
        Wizard.addPage(self.disk_config_page)
        self.project_name_page = QtGui.QWizardPage()
        self.project_name_page.setObjectName("project_name_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.project_name_page)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.project_name = QtGui.QLineEdit(self.project_name_page)
        self.project_name.setObjectName("project_name")
        self.verticalLayout_3.addWidget(self.project_name)
        self.project_directories = QtGui.QLabel(self.project_name_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_directories.sizePolicy().hasHeightForWidth())
        self.project_directories.setSizePolicy(sizePolicy)
        self.project_directories.setFrameShape(QtGui.QFrame.NoFrame)
        self.project_directories.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.project_directories.setObjectName("project_directories")
        self.verticalLayout_3.addWidget(self.project_directories)
        Wizard.addPage(self.project_name_page)
        self.config_location_page = QtGui.QWizardPage()
        self.config_location_page.setObjectName("config_location_page")
        self.gridLayout_3 = QtGui.QGridLayout(self.config_location_page)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.windows_label = QtGui.QLabel(self.config_location_page)
        self.windows_label.setObjectName("windows_label")
        self.gridLayout_3.addWidget(self.windows_label, 2, 0, 1, 1)
        self.linux_label = QtGui.QLabel(self.config_location_page)
        self.linux_label.setObjectName("linux_label")
        self.gridLayout_3.addWidget(self.linux_label, 3, 0, 1, 1)
        self.linux_path = QtGui.QLineEdit(self.config_location_page)
        self.linux_path.setObjectName("linux_path")
        self.gridLayout_3.addWidget(self.linux_path, 3, 2, 1, 1)
        self.windows_path = QtGui.QLineEdit(self.config_location_page)
        self.windows_path.setObjectName("windows_path")
        self.gridLayout_3.addWidget(self.windows_path, 2, 2, 1, 1)
        self.mac_path = QtGui.QLineEdit(self.config_location_page)
        self.mac_path.setObjectName("mac_path")
        self.gridLayout_3.addWidget(self.mac_path, 0, 2, 1, 1)
        self.mac_label = QtGui.QLabel(self.config_location_page)
        self.mac_label.setObjectName("mac_label")
        self.gridLayout_3.addWidget(self.mac_label, 0, 0, 1, 1)
        self.mac_browse = QtGui.QPushButton(self.config_location_page)
        self.mac_browse.setEnabled(False)
        self.mac_browse.setObjectName("mac_browse")
        self.gridLayout_3.addWidget(self.mac_browse, 0, 3, 1, 1)
        self.windows_browse = QtGui.QPushButton(self.config_location_page)
        self.windows_browse.setEnabled(False)
        self.windows_browse.setObjectName("windows_browse")
        self.gridLayout_3.addWidget(self.windows_browse, 2, 3, 1, 1)
        self.linux_browse = QtGui.QPushButton(self.config_location_page)
        self.linux_browse.setEnabled(False)
        self.linux_browse.setObjectName("linux_browse")
        self.gridLayout_3.addWidget(self.linux_browse, 3, 3, 1, 1)
        Wizard.addPage(self.config_location_page)
        self.progress_page = QtGui.QWizardPage()
        self.progress_page.setSubTitle("")
        self.progress_page.setObjectName("progress_page")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.progress_page)
        self.verticalLayout_4.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.setup_label = QtGui.QLabel(self.progress_page)
        self.setup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.setup_label.setObjectName("setup_label")
        self.verticalLayout_4.addWidget(self.setup_label)
        spacerItem6 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.progress_bar = QtGui.QProgressBar(self.progress_page)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_4.addWidget(self.progress_bar)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        Wizard.addPage(self.progress_page)
        self.complete_page = QtGui.QWizardPage()
        self.complete_page.setSubTitle("")
        self.complete_page.setObjectName("complete_page")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.complete_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.complete_label = QtGui.QLabel(self.complete_page)
        self.complete_label.setAlignment(QtCore.Qt.AlignCenter)
        self.complete_label.setObjectName("complete_label")
        self.verticalLayout_5.addWidget(self.complete_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkmark = QtGui.QLabel(self.complete_page)
        self.checkmark.setMaximumSize(QtCore.QSize(80, 80))
        self.checkmark.setText("")
        self.checkmark.setPixmap(QtGui.QPixmap(":/res/checkmark.png"))
        self.checkmark.setScaledContents(True)
        self.checkmark.setAlignment(QtCore.Qt.AlignCenter)
        self.checkmark.setObjectName("checkmark")
        self.horizontalLayout.addWidget(self.checkmark)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        Wizard.addPage(self.complete_page)
        self.label_standard.setBuddy(self.select_standard)
        self.label_project.setBuddy(self.select_project)
        self.label_github.setBuddy(self.select_github)
        self.label_disk.setBuddy(self.select_disk)
        self.octocat.setBuddy(self.github_url)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)
        Wizard.setTabOrder(self.select_standard, self.select_project)
        Wizard.setTabOrder(self.select_project, self.select_github)
        Wizard.setTabOrder(self.select_github, self.select_disk)
        Wizard.setTabOrder(self.select_disk, self.project_list)
        Wizard.setTabOrder(self.project_list, self.github_url)
        Wizard.setTabOrder(self.github_url, self.path)
        Wizard.setTabOrder(self.path, self.browse_button)
        Wizard.setTabOrder(self.browse_button, self.project_name)
        Wizard.setTabOrder(self.project_name, self.mac_path)
        Wizard.setTabOrder(self.mac_path, self.mac_browse)
        Wizard.setTabOrder(self.mac_browse, self.windows_path)
        Wizard.setTabOrder(self.windows_path, self.windows_browse)
        Wizard.setTabOrder(self.windows_browse, self.linux_path)
        Wizard.setTabOrder(self.linux_path, self.linux_browse)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_type_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Select Configuration Type</font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_type_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.select_standard.setText(QtGui.QApplication.translate("Wizard", "Standard Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_standard.setText(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sit", None, QtGui.QApplication.UnicodeUTF8))
        self.select_project.setText(QtGui.QApplication.translate("Wizard", "Use Another Project\'s Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_project.setText(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sit", None, QtGui.QApplication.UnicodeUTF8))
        self.select_github.setText(QtGui.QApplication.translate("Wizard", "Use a Configuration from Github", None, QtGui.QApplication.UnicodeUTF8))
        self.label_github.setText(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sit", None, QtGui.QApplication.UnicodeUTF8))
        self.select_disk.setText(QtGui.QApplication.translate("Wizard", "Use a Configuration from Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_disk.setText(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sit", None, QtGui.QApplication.UnicodeUTF8))
        self.project_config_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Select Project</font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.project_config_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.github_config_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Select GitHub URL</font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.github_config_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.github_url.setText(QtGui.QApplication.translate("Wizard", "https://www.github.com/", None, QtGui.QApplication.UnicodeUTF8))
        self.github_url.setPlaceholderText(QtGui.QApplication.translate("Wizard", "GitHub URL", None, QtGui.QApplication.UnicodeUTF8))
        self.disk_config_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Select Source Path</font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.disk_config_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.path.setPlaceholderText(QtGui.QApplication.translate("Wizard", "/Path/To/Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_button.setText(QtGui.QApplication.translate("Wizard", "&Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.project_name_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Enter Project Name </font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.project_name_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.project_name.setPlaceholderText(QtGui.QApplication.translate("Wizard", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.project_directories.setText(QtGui.QApplication.translate("Wizard", "<html><head/><body><p><span style=\" font-size:large;\">Project Directories will be:</span></p><p>/mnt/foo/bar</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_location_page.setTitle(QtGui.QApplication.translate("Wizard", "<p></p><font size=18>Select Config Location</font><p></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_location_page.setSubTitle(QtGui.QApplication.translate("Wizard", "Lorem ispum dolor sitLorm ispum dolor sit Lorem", None, QtGui.QApplication.UnicodeUTF8))
        self.windows_label.setText(QtGui.QApplication.translate("Wizard", "Windows:", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_label.setText(QtGui.QApplication.translate("Wizard", "Linux:", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_path.setPlaceholderText(QtGui.QApplication.translate("Wizard", "/path/on/linux", None, QtGui.QApplication.UnicodeUTF8))
        self.windows_path.setPlaceholderText(QtGui.QApplication.translate("Wizard", "\\\\Path\\On\\Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_path.setPlaceholderText(QtGui.QApplication.translate("Wizard", "/Path/On/Mac", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_label.setText(QtGui.QApplication.translate("Wizard", "Mac:", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_browse.setText(QtGui.QApplication.translate("Wizard", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.windows_browse.setText(QtGui.QApplication.translate("Wizard", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_browse.setText(QtGui.QApplication.translate("Wizard", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_label.setText(QtGui.QApplication.translate("Wizard", "<html><head/><body><p><span style=\" font-size:26pt;\">Setting Up Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.complete_label.setText(QtGui.QApplication.translate("Wizard", "<html><head/><body><p><span style=\" font-size:26pt;\">Project Setup Complete</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
